name: production

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      build_script: build-production
      artifact_name: production-build-tracking-web

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment_name: production
      artifact_name: production-build-tracking-web
      s3_bucket: production-prochain
      s3_prefix: www/tracking-web
    secrets: inherit
