name: staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      build_script: build-staging
      artifact_name: staging-build-tracking-web

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment_name: staging
      artifact_name: staging-build-tracking-web
      s3_bucket: staging-prochain
      s3_prefix: www/tracking-web
    secrets: inherit
